---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.6-alpine
inputs:
  - name: pybot
outputs:
  - name: coverage
run:
  dir: pybot
  path: sh
  args:
    - -ec
    - |
      pip -q install pytest
      pip -q install pytest-cov
      pip -q install -r requirements
      cd bot
      mkdir config
      cat <<EOF >./config/config.test.yaml
      tokens:
        weather_token: "${WEATHER_TOKEN}"
        tg_token: "${TG_TOKEN}"
      telegram:
        mode: Polling
      database:
        host: data/pybot.test.db
      admins:
        - test_one
      EOF
      python -m pytest --cov=. --cov-report html --cov-config .coveragerc --log-cli-level 1 --basetemp=temp tests/
      cp -r ../dockerfile/coverage.Dockerfile ../dockerfile/conf.d htmlcov ../../coverage/
