#Test
version: "3"
services:

    yoba:
        image: cuttlerat/yoba
        build:
            context: .
            dockerfile: dockerfile/yoba.Dockerfile
        volumes:
          - ./bot/data:/yoba/data
          - ./bot/config:/yoba/config:ro
        restart: always
