version: "3"
services:

    pybot_preinstall:
        image: pybot_preinstall
        build:
            context: .
            dockerfile: dockerfiles/pybot_preinstall.Dockerfile

    pybot:
        image: pybot
        build:
            context: .
            dockerfile: dockerfiles/pybot.Dockerfile
        volumes:
          - ./data:/pybot/data
          - ./tokens:/pybot/tokens:ro
        restart: unless-stopped
        depends_on:
          - pybot_preinstall

    builder:
        image: builder
        build:
            context: .
            dockerfile: dockerfiles/builder.Dockerfile
        volumes:
          - .:/pybot
          - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
