version: "3"
services:

    pybot:
        image: pybot
        build:
            context: .
            dockerfile: dockerfiles/pybot.Dockerfile
        volumes:
          - ./bot/data:/pybot/data
          - ./bot/tokens:/pybot/tokens:ro
        restart: always
