#Test
version: "3"
services:

    pybot:
        image: cuttlerat/pybot
        build:
            context: .
            dockerfile: dockerfile/pybot.Dockerfile
        volumes:
          - ./bot/data:/pybot/data
          - ./bot/config:/pybot/config:ro
        restart: always
