version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/yoba.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/yoba.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker image ls
            docker build \
                --cache-from=cuttlerat/yoba \
                -t "cuttlerat/yoba:${CIRCLE_BRANCH}" \
                -f "./dockerfile/yoba.Dockerfile" .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/yoba.tar "cuttlerat/yoba:${CIRCLE_BRANCH}"
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/yoba.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "issue-115" ]; then
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              #docker tag "cuttlerat/yoba:master" "cuttlerat/yoba:latest"
              docker push "cuttlerat/yoba"
            fi
